version: '3'
services:
  db:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    volumes:
      - ./db/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'

#  back:
#    depends_on:
#      - db
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    ports:
#      - 5500:5000

  adminer:
    image: adminer
    ports:
      - 8580:8080

