version: '3'
services:
  db:
    image: 'mysql:latest'
    ports:
      - 3308:3306
    volumes:
      - ./Antiplagiat-Back/db/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'

  back:
    image: antiplagiat-back
    depends_on:
      - db
    build:
      context: ./Antiplagiat-Back
      dockerfile: Dockerfile
    ports:
      - 5500:5000

  web:
    image: antiplagiat-front
    build:
      context: ./Antiplagiat-Front
      dockerfile: Dockerfile
    ports:
      - 3500:3000

  adminer:
    image: adminer
    ports:
      - 8500:8080

